version: '3.8'

services:
  calculator-app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: calculator-container
    ports:
      - "5000:5000"
    volumes:
      - ./calculator_app/data:/app/calculator_app/data
      - ./logs:/app/logs      
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=production

      - CONTAINER_MODE=true
      - CONTAINER_USERNAME=user
      - CONTAINER_PASSWORD=user123

      - SECRET_KEY=your-production-secret-key
    stdin_open: true
    tty: true
